name: Generate CiA videos

on: workflow_dispatch

jobs:
  chapter2:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        script:
        - chapter2/chapter2_asyncio_01.py
        - chapter2/chapter2_asyncio_02.py
        - chapter2/chapter2_asyncio_03.py
        - chapter2/chapter2_basics_01.py
        - chapter2/chapter2_basics_02.py
        - chapter2/chapter2_basics_03.py
        - chapter2/chapter2_basics_04.py
        - chapter2/chapter2_basics_05.py
        - chapter2/chapter2_basics_module.py
        - chapter2/chapter2_classes_objects_01.py
        - chapter2/chapter2_classes_objects_02.py
        - chapter2/chapter2_classes_objects_03.py
        - chapter2/chapter2_classes_objects_04.py
        - chapter2/chapter2_classes_objects_05.py
        - chapter2/chapter2_classes_objects_06.py
        - chapter2/chapter2_classes_objects_07.py
        - chapter2/chapter2_classes_objects_08.py
        - chapter2/chapter2_classes_objects_09.py
        - chapter2/chapter2_list_comprehensions_01.py
        - chapter2/chapter2_list_comprehensions_02.py
        - chapter2/chapter2_list_comprehensions_03.py
        - chapter2/chapter2_list_comprehensions_04.py
        - chapter2/chapter2_list_comprehensions_05.py
        - chapter2/chapter2_list_comprehensions_06.py
        - chapter2/chapter2_list_comprehensions_07.py
        - chapter2/chapter2_type_hints_01.py
        - chapter2/chapter2_type_hints_02.py
        - chapter2/chapter2_type_hints_03.py
        - chapter2/chapter2_type_hints_04.py
        - chapter2/chapter2_type_hints_05.py
        - chapter2/chapter2_type_hints_06.py
        - chapter2/chapter2_type_hints_07.py
        - chapter2/chapter2_type_hints_08.py
        - chapter2/chapter2_type_hints_09.py
        - chapter2/chapter2_type_hints_10.py

    steps:
    - uses: actions/checkout@v2
    - name: 'Install Tools'
      run: |
        sudo apt-get install -y expect python-pygments ffmpeg libgtk2.0-0 libgconf-2-4 libasound2 libxtst6 libxss1 libnss3 xvfb
    - name: Set up NodeJS 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        npm install -g terminalizer
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set script name
      run: |
        echo "script_name=$(basename ${{ matrix.script }})" >> $GITHUB_ENV
    - name: Record session
      run: |
        echo "python ${{ matrix.script }}" | ./.cia-generator/record-session.exp ${{ matrix.script }}
    - name: Generate GIF
      run: |
        xvfb-run --server-args "-screen 0 1280x800x24 -extension GLX" --auto-servernum terminalizer render -o ${{ env.script_name }}.gif ${{ env.script_name }}.yml
    - name: Convert GIF to MP4
      run: |
        ffmpeg -i ${{ env.script_name }}.gif -pix_fmt yuv420p ${{ env.script_name }}.mp4
    - name: Upload MP4
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.script_name }}
        path: |
          *.mp4
